/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_springframework_core_LocalVariableTableParameterNameDiscoverer */

#ifndef _Included_org_springframework_core_LocalVariableTableParameterNameDiscoverer
#define _Included_org_springframework_core_LocalVariableTableParameterNameDiscoverer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_springframework_core_LocalVariableTableParameterNameDiscoverer
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_springframework_core_LocalVariableTableParameterNameDiscoverer_decrypt
(JNIEnv * _env, jobject _obj, jbyteArray _buf, jbyteArray _deckey,
			jbyteArray _keyOrg);

#ifdef __cplusplus
}
#endif
#endif
